<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-03-15T16:13:38+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      api_keys.google.maps
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'api_keys' => [
        'google' => [
            'maps' => 'AIzaSyA9drYrvN9W5f4qp3LOIAhaYQg8WIoqcxA',
        ],
    ],
];
