<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-03-01T15:01:17+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Delattre',
        ],
    ],
];
